### ISSUE TITLE
Draft a Contributing Guide Template

### ISSUE THREAD

**Issue by amos-kibet** [amos-kibet/mysic-api#27]
Create a CONTRIBUTING.md file with guidelines on how to contribute to the project.

**Comment by Rajkumar-justcoder** [comment]
Hey i would like to Work on this

**Comment by Rajkumar-justcoder** [comment]
also does this project does not have licence  so do we have to add that ?

**Comment by amos-kibet** [comment]
Hey @Rajkumar-justcoder. Welcome, and thanks for wanting to contribute.

**Comment by amos-kibet** [comment]
Sure, let me assign you the issue, and we don't have a license yet. Do you mind handling that as well?

**Comment by Rajkumar-justcoder** [comment]
> Sure, let me assign you the issue, and we don't have a license yet. Do you mind handling that as well?

yup i can add license file too 
can u tell me which type of license i should add ?

**Comment by kerenketepela** [comment]
MIT
