### ISSUE TITLE
Create an .env.example template file

### ISSUE THREAD

**Issue by amos-kibet** [amos-kibet/mysic-api#29]
This file will guide anyone cloning this repo to reproduce environment variables, replacing the examples with their own.

**Comment by Rajkumar-justcoder** [comment]
Hey i would like to work on this 
and also what about adding pr template 
like this ( same ) 
![image](https://user-images.githubusercontent.com/83064473/194926931-cdb5a177-b117-4ca9-beac-a9e7ef14e3df.png)

**Comment by amos-kibet** [comment]
> Hey i would like to work on this and also what about adding pr template like this ( same ) ![image](https://user-images.githubusercontent.com/83064473/194926931-cdb5a177-b117-4ca9-beac-a9e7ef14e3df.png)

Sure, pick up the issue.
Also, the pr template will be a good addition

**Comment by Rajkumar-justcoder** [comment]
Should i remove this thing from readme.md 
![image](https://user-images.githubusercontent.com/83064473/194930542-b792b7cb-025c-42a8-8b7c-ad0d104f5631.png)
and add section to head over to contributing.md file

**Comment by Rajkumar-justcoder** [comment]
like this 
## Contribution Guidelines 🏗

Want to add your inputs to the repo? We invite you to contribute.

Head to [CONTRIBUTING.md](./CONTRIBUTING.md) to start contributing.

**Comment by amos-kibet** [comment]
> Should i remove this thing from readme.md ![image](https://user-images.githubusercontent.com/83064473/194930542-b792b7cb-025c-42a8-8b7c-ad0d104f5631.png) and add section to head over to contributing.md file

Yes, remove that and leave a link to contributing
