### ISSUE TITLE
Configure account activation via email

### ISSUE THREAD

**Issue by amos-kibet** [amos-kibet/mysic-api#4]
Implement an option where user receives an email upon sign up to activate account.

**Comment by kerenketepela** [comment]
Will make a PR by end of weekend. is that OK

**Comment by amos-kibet** [comment]
That's fine, thanks man.

**Comment by amos-kibet** [comment]
Account activation endpoint can go to another issue.

**Comment by amos-kibet** [comment]
Reopening since we migrated to MongoDB
